name = "gulvet"
compatibility_date = "2025-04-05"
main = "index.html"

[site]
bucket = "./"

[build]
command = ""

[env.production]
name = "gulvet-prod"
workers_dev = false
route = "gulvet.com/*"

[env.staging]
name = "gulvet-staging"
workers_dev = true
